image: node:8-alpine

variables:
  PUBLISH_PATH: 'dist/'

stages:
  - build-test
  - release

build-test:
  stage: build-test
  artifacts:
    name: '${CI_COMMIT_SHA}'
    paths:
      - ${PUBLISH_PATH}
  script:
    - yarn
    - yarn run build
    - yarn run test

release:
  stage: release
  script:
    - cd ${PUBLISH_PATH}
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish
  only:
    - tags
